### ISSUE TITLE
Need to get tank names when getting tanks that are being sold

### ISSUE THREAD

**Issue by JorgeVidal29** [RickLeinecker/Fortuna#227]
**Describe the solution you'd like**
When I get the list of tanks that are being sold I need a way to get the name to display.

Currently what is being returned for tank sales posts are their object IDs.

**Comment by Derplime** [comment]
Updated naming of this issue to clear up confusion. Also, the implementation I'm going with is just creating a new route specifically for getting the list of tank sales not belonging to the user.

This will isolate a specific use case instead of making one API call do a lot of things. The general `getMarketSales` can still be used for components (and Casus blocks), due to the "non-existent" nature of them from an DB object storage perspective.
