### ISSUE TITLE
Passing parent component's state into child component's props.

### ISSUE THREAD

**Issue by blaiadam** [RickLeinecker/Fortuna#271]
**Describe the bug**
When you pass a value from a parent component's state into a child component's props, React gets weird.

**To Reproduce**
1. Download the GetUserTanks branch.
2. Go to Armory.
3. View errors.

**Expected behavior**
We need to remove props from the child components that come from the parent's state.

**Screenshots**
![image](https://user-images.githubusercontent.com/42626045/77812735-ab914700-7079-11ea-93c5-22fdc93f09d6.png)

**Additional context**
Check this out for more information. https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by SecondThread** [comment]
I think you are misinterpreting the error message here. Passing data from the parent's state to a child's props is fine and happens all the time. The issue is that you are trying to use a method `componentWillReceiveProps`  that is old and they are trying to get rid of. If you find a different way of doing this that doesn't use that method, the warning will go away.
